### ISSUE TITLE
[Question] Compatibility with Odin Inspector?

### ISSUE THREAD

**Issue by MostHated** [SisusCo/Power-Inspector-Public#5]
Hey there,
  I came across your asset and thought it seemed rather interesting. My only concern is compatibility with Odin Inspector, do you happen to know if there is any sort of confliction? Both assets do fairly different stuff but I am sure there is probably some overlap, but not sure if that is going to cause an issue.

Thanks,
-MH

**Comment by timo-sisus** [comment]
Hi MostHated

Thank you for your question. Your guess is very accurate! They work quite well together, but there's some overlap, which means you will lose some of the features of Power Inspector as a trade-off, if you wish to also use Odin.

There's a preference item called [Use Editors Over GUI Instructions](https://docs.sisus.co/power-inspector/preferences/use-editors-over-guiinstructions/)  that has been added specifically to tackle the issue of this kind of overlap.
It can be used to make Power Inspector prefer using Editors over its internal [GUI Instructions](https://docs.sisus.co/power-inspector/terminology/gui-instructions/) when drawing class members, which in this case allows Odin to take over in the drawing all the class members.

If the switch to Editors does not happen automatically with the default option, you can set the preference item to "Always".

Basically when using Editors you lose functionality of Power Inspector that takes place on the class member level, while still retaining all functionality that happens on higher levels.

What still works when using Editors:
- [Navigation buttons](https://docs.sisus.co/power-inspector/features/navigation-buttons/) work as usual.
- [Filter field](https://docs.sisus.co/power-inspector/features/filter-field/) still works. It will temporarily switch back to using GUI instructions during filtering, and then switch right back to using Editors.
- [Split View](https://docs.sisus.co/power-inspector/features/split-view/) works as usual. Peeking will however stop working for class members. But it still works from the hierarchy and project windows.
- Headers of Unity Objects retain their normal functionality, including having custom context menus and toolbar items. This means that the [Quick Invoke Menu button](https://docs.sisus.co/power-inspector/features/quick-invoke-menu/) can still be used from the toolbar.
- [Debug Mode+](https://docs.sisus.co/power-inspector/features/debug-mode/) still works. GUI instructions will be used instead of Editors when this mode is active.

What won't work when using Editors:
- Custom context menu items for class members will mostly no longer appear. However "Reset", "Copy" and "Paste" can still be used in many cases.
- You lose functionality of [special class member GUI Instructions](https://docs.sisus.co/power-inspector/category/enhanced-gui-instructions/).
- Intuitive keyboard arrow key navigation becomes less reliable, since it no longer has perfect knowledge of the hierarchies of GUI elements.

I hope that answers you question! Let me know if you still have any questions left.

Timo Naskali
Sisus
